name: AWS Security Scanner CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest boto3 bandit

      - name: Run Linting
        run: |
          flake8 src tests --max-line-length=100

      - name: Run Unit Tests
        run: |
          pytest tests/

      - name: Security Scan (Bandit)
        run: |
          bandit -r src/ -ll

  package:
    name: Package Lambda Deployment (Optional)
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Package Lambda Function
        run: |
          zip -r lambda_function.zip src/ deployment/lambda_function.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_package
          path: lambda_function.zip
