name: AWS Security Scanner CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  test:
    name: Run Unit Tests & Security Checks
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read

    env:
      NODE_OPTIONS: '--no-warnings' # Suppresses AWS SDK v2 warning

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::418295677815:role/GitHubActionsRole
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

  deploy:
    needs: test # Ensures 'deploy' runs only after 'test' completes successfully
    uses: OWNER/REPO/.github/workflows/deploy.yaml@main # Calls the deploy workflow
