name: AWS Security Scanner CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  test:
    name: Run Unit Tests & Security Checks
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read

    env:
      NODE_OPTIONS: '--no-warnings' # Suppresses AWS SDK v2 warning

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Enables caching of dependencies

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "⚠️ No requirements.txt found, skipping..."; fi

      - name: Run Tests
        run: |
          if [ -d tests ]; then pytest tests/; else echo "⚠️ No tests directory found, skipping tests."; fi

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yaml
